---
# Copyright (c) 2019-2020 Petr Vorel <pvorel@suse.cz>

sudo: required
language: c
services:
    - docker

matrix:
    include:
        - os: linux
          env: DISTRO=ubuntu:groovy
          compiler: gcc

        - os: linux
          env: DISTRO=ubuntu:xenial EXTRA_BUILD_OPTS='-DUSE_GETTEXT=false'
          compiler: clang

before_install:
    - DIR="/usr/src/iputils"
    - printf "FROM $DISTRO\nRUN mkdir -p $DIR\nWORKDIR $DIR\nCOPY . $DIR\n" > Dockerfile
    - echo "cat Dockerfile"; cat Dockerfile
    - docker build -t iputils .

script:
    - INSTALL="${DISTRO%%:*}"
    - INSTALL="${INSTALL%%/*}"
    - DISTRO_VERSION="${DISTRO#*:}"
    - case $VARIANT in cross-compile*) BUILD="cross";; i386) BUILD="32";; *) BUILD="native";; esac
    - docker run -it iputils /bin/sh -c "cd travis && DISTRO_VERSION=\"$DISTRO_VERSION\" ./$INSTALL.sh && if [ \"$VARIANT\" ]; then ARCH=\"$ARCH\" ./$INSTALL.$VARIANT.sh; fi && CC=$CC EXTRA_BUILD_OPTS=\"$EXTRA_BUILD_OPTS\" ../build.sh"
